//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIH.RT.TMS.HL7Server
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PatientFeedV3
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatientFeedV3()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIH.XDS.BusinessLogic.PatientIdentityFeed.PatientFeedV3", typeof(PatientFeedV3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;MCCI_IN000002UV01 xmlns=&quot;urn:hl7-org:v3&quot; ITSVersion=&quot;XML_1.0&quot;&gt;&lt;id root=&quot;$NEW.GUID$&quot;/&gt;&lt;creationTime value=&quot;$creationTime$&quot;/&gt;&lt;interactionId root=&quot;$INTERACTION.ID$&quot; extension=&quot;MCCI_IN000002UV01&quot;/&gt;&lt;processingCode code=&quot;P&quot;/&gt;&lt;processingModeCode code=&quot;R&quot;/&gt;&lt;acceptAckCode code=&quot;NE&quot;/&gt;&lt;receiver typeCode=&quot;RCV&quot;&gt;&lt;device determinerCode=&quot;INSTANCE&quot;&gt;&lt;id root=&quot;$RECEIVER.ROOT$&quot;/&gt;&lt;/device&gt;&lt;/receiver&gt;&lt;sender typeCode=&quot;SND&quot;&gt;&lt;device determinerCode=&quot;INSTANCE&quot;&gt;&lt;id root=&quot;$SENDER.ROOT$&quot;/&gt;&lt;/device [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PatientAddAck
        {
            get
            {
                return ResourceManager.GetString("PatientAddAck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;MCCI_IN000002UV01 xmlns=&quot;urn:hl7-org:v3&quot; ITSVersion=&quot;XML_1.0&quot;&gt;&lt;id root=&quot;$NEW.GUID$&quot;/&gt;&lt;creationTime value=&quot;$creationTime$&quot;/&gt;&lt;interactionId root=&quot;$INTERACTION.ID$&quot; extension=&quot;MCCI_IN000002UV01&quot;/&gt;&lt;processingCode code=&quot;P&quot;/&gt;&lt;processingModeCode code=&quot;R&quot;/&gt;&lt;acceptAckCode code=&quot;NE&quot;/&gt;&lt;receiver typeCode=&quot;RCV&quot;&gt;&lt;device determinerCode=&quot;INSTANCE&quot;&gt;&lt;id root=&quot;$RECEIVER.ROOT$&quot;/&gt;&lt;/device&gt;&lt;/receiver&gt;&lt;sender typeCode=&quot;SND&quot;&gt;&lt;device determinerCode=&quot;INSTANCE&quot;&gt;&lt;id root=&quot;$SENDER.ROOT$&quot;/&gt;&lt;/device [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PatientDuplicatedResolvedAck
        {
            get
            {
                return ResourceManager.GetString("PatientDuplicatedResolvedAck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;MCCI_IN000002UV01 xmlns=&quot;urn:hl7-org:v3&quot; ITSVersion=&quot;XML_1.0&quot;&gt;&lt;id root=&quot;$NEW.GUID$&quot;/&gt;&lt;creationTime value=&quot;$creationTime$&quot;/&gt;&lt;interactionId root=&quot;$INTERACTION.ID$&quot; extension=&quot;MCCI_IN000002UV01&quot;/&gt;&lt;processingCode code=&quot;P&quot;/&gt;&lt;processingModeCode code=&quot;R&quot;/&gt;&lt;acceptAckCode code=&quot;NE&quot;/&gt;&lt;receiver typeCode=&quot;RCV&quot;&gt;&lt;device determinerCode=&quot;INSTANCE&quot;&gt;&lt;id root=&quot;$RECEIVER.ROOT$&quot;/&gt;&lt;/device&gt;&lt;/receiver&gt;&lt;sender typeCode=&quot;SND&quot;&gt;&lt;device determinerCode=&quot;INSTANCE&quot;&gt;&lt;id root=&quot;$SENDER.ROOT$&quot;/&gt;&lt;/device [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PatientRevisedAck
        {
            get
            {
                return ResourceManager.GetString("PatientRevisedAck", resourceCulture);
            }
        }
    }
}
